apiVersion: webhookconfig.keptn.sh/v1beta1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.enable-feature.triggered
      requests:
        - url: https://api.github.com/repos/my-keptn-tests/fibonacci/dispatches
          payload: >-
            {"event_type":"enable-feature","client_payload":{"type":"{{.type}}","project":"{{.data.project}}","service":"{{.data.service}}","stage":"{{.data.stage}}","shkeptncontext":"{{.shkeptncontext}}","id":"{{.id}}"}}
          headers:
            - key: Authorization
              value: token {{.env.secret_githubsecret_GITHUBTOKEN}}
          method: POST
      envFrom:
        - name: secret_githubsecret_GITHUBTOKEN
          secretRef:
            name: github-secret
            key: GITHUBTOKEN
      subscriptionID: 2c214186-3a7e-4333-a44d-fa581110ce54
      sendFinished: false
      sendStarted: true
    - type: sh.keptn.event.notify.triggered
      requests:
        - url: "{{.env.secret_slackhook_key}}"
          payload: >2-
                payload={         "channel" : "{{.data.project}}--{{.data.service}}",        "username" : "keptn",         "blocks": [            {            "type" : "section",            "text" : {                "type": "mrkdwn",                "text" : "*Delivery failed*"            }            },            {            "type" : "section",            "text" : {                "type": "mrkdwn",                "text" : "*Project:* {{.data.project}}\n*Stage:* {{.data.stage}}\n*Service:* {{.data.service}}\n*Traces in Jaeger:* "            }            }        ]    }
          headers: []
          method: POST
      envFrom:
        - name: secret_slackhook_key
          secretRef:
            name: slack-hook
            key: key
      subscriptionID: e5841271-5539-4517-8882-965f253e8125
      sendFinished: true
      sendStarted: true
    - type: sh.keptn.event.release.finished
      requests:
        - url: "{{.env.secret_slackhook_key}}"
          payload: >2-
                payload={         "channel" : "{{.data.project}}--{{.data.service}}",        "username" : "keptn",         "blocks": [            {            "type" : "section",            "text" : {                "type": "mrkdwn",                "text" : "*Release finished*"            }            },            {            "type" : "section",            "text" : {                "type": "mrkdwn",                "text" : "*Project:* {{.data.project}}\n*Stage:* {{.data.stage}}\n*Service:* {{.data.service}}\n            }            }        ]    }
          headers: []
          method: POST
      envFrom:
        - name: secret_slackhook_key
          secretRef:
            name: slack-hook
            key: key
      subscriptionID: 843c65dc-38e1-4a02-b023-a49f394db0e8
      sendFinished: false
      sendStarted: false
