apiVersion: webhookconfig.keptn.sh/v1beta1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.notify.triggered
      requests:
        - url: https://webhook.site/23c4b648-3c4e-4915-b2e4-f35306ad1296
          payload: >-
            { notification }
          headers: []
          method: POST
      subscriptionID: e5841271-5539-4517-8882-965f253e8125
      sendFinished: true
      sendStarted: true
    - type: sh.keptn.event.enable-feature.triggered
      requests:
        - url: https://api.github.com/repos/my-keptn-tests/fibonacci/dispatches
          payload: >-
            {"event_type":"active","client_payload":{"type":"{{.type}}","project":"{{.data.project}}","service":"{{.data.service}}","stage":"{{.data.stage}}","data":"{{.data.custom}}","shkeptncontext":"{{.shkeptncontext}}","id":"{{.id}}"}}
          headers: []
          method: POST
      subscriptionID: 2c214186-3a7e-4333-a44d-fa581110ce54
      sendFinished: false
      sendStarted: true
