apiVersion: webhookconfig.keptn.sh/v1beta1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.enable-feature.triggered
      requests:
        - url: https://api.github.com/repos/my-keptn-tests/fibonacci/dispatches
          payload: >-
            {"event_type":"enable-feature","client_payload":{"type":"{{.type}}","project":"{{.data.project}}","service":"{{.data.service}}","stage":"{{.data.stage}}","shkeptncontext":"{{.shkeptncontext}}","id":"{{.id}}","default_variant":"on","flag_key":"use-remote-fib-service"}}
          headers:
            - key: Authorization
              value: token {{.env.secret_githubsecret_GITHUBTOKEN}}
          method: POST
      envFrom:
        - name: secret_githubsecret_GITHUBTOKEN
          secretRef:
            name: github-secret
            key: GITHUBTOKEN
      subscriptionID: 2c214186-3a7e-4333-a44d-fa581110ce54
      sendFinished: false
      sendStarted: true
    - type: sh.keptn.event.notify.triggered
      requests:
        - url: https://hooks.slack.com/services/{{.env.secret_slacksecret_HOOK}}
          payload: >-
            {"text":"Delivery of {{.data.configurationChange.values.image}} failed :x:","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"Delivery of {{.data.configurationChange.values.image}} failed :x:"},"accessory":{"type":"button","text":{"type":"plain_text","text":"Open Jaeger to see traces","emoji":true},"value":"click_me_123","url":"http://jaeger-query.jaeger.34.122.159.72.nip.io/search","action_id":"button-action"}}]}
          headers: []
          method: POST
      envFrom:
        - name: secret_slacksecret_HOOK
          secretRef:
            name: slack-secret
            key: HOOK
      subscriptionID: e5841271-5539-4517-8882-965f253e8125
      sendFinished: true
      sendStarted: true
    - type: sh.keptn.event.release.finished
      requests:
        - url: https://hooks.slack.com/services/{{.env.secret_slacksecret_HOOK}}
          payload: >-
            {"text":"Release in {{.data.stage}} finished with the new feature enabled :white_check_mark:"}
          headers: []
          method: POST
      envFrom:
        - name: secret_slacksecret_HOOK
          secretRef:
            name: slack-secret
            key: HOOK
      subscriptionID: 843c65dc-38e1-4a02-b023-a49f394db0e8
      sendFinished: false
      sendStarted: false
