apiVersion: webhookconfig.keptn.sh/v1beta1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.release.finished
      requests:
        - url: https://hooks.slack.com/services/{{.env.secret_slacksecret_HOOK}}
          payload: >-
            {"text":"Release in {{.data.stage}} finished, feature enabled"}
          headers: []
          method: POST
      envFrom:
        - name: secret_slacksecret_HOOK
          secretRef:
            name: slack-secret
            key: HOOK
      subscriptionID: 843c65dc-38e1-4a02-b023-a49f394db0e8
      sendFinished: false
      sendStarted: false
    - type: sh.keptn.event.notify.triggered
      requests:
        - url: https://hooks.slack.com/services/{{.env.secret_slacksecret_HOOK}}
          payload: >-
            {"text":"Delivery failed.","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"Delivery failed."},"accessory":{"type":"button","text":{"type":"plain_text","text":"Open Jaeger","emoji":true},"value":"click_me_123","url":"http://localhost:8080/search","action_id":"button-action"}}]}
          headers: []
          method: POST
      envFrom:
        - name: secret_slacksecret_HOOK
          secretRef:
            name: slack-secret
            key: HOOK
      subscriptionID: e5841271-5539-4517-8882-965f253e8125
      sendFinished: true
      sendStarted: true
