apiVersion: v2
actions:
  - name: "Run k6"
    events:
      - name: "sh.keptn.event.test.triggered"
    tasks:
      - name: "Run k6 with Keptn"
        files:
          - /k6
        image: "loadimpact/k6"
        cmd: ["k6"]
        args: ["run", "BASE_URL", "http://localhost:30000", "--duration", "30s", "--vus", "60", "/keptn/k6/calculate.js"]