name: Enable Feature
on:
  repository_dispatch:
    types: 
      - enable-feature
jobs:
  test:
    name: Enable Feature
    runs-on: ubuntu-latest
    steps:
    - name: my active task
      run: |
        echo "Received active webhook, displaying received data"
        echo "type = ${{ github.event.client_payload.type }}"
        echo "shkeptncontext = ${{ github.event.client_payload.shkeptncontext }}"
        echo "id = ${{ github.event.client_payload.id }}"
    - name: send finished event
      run: |
        echo "Received active webhook, will send back Keptn finished event"
        json=$(cat <<-END
            {
              "data": {
                "project":"${{ github.event.client_payload.project }}",
                "stage": "${{ github.event.client_payload.stage}}",
                "service": "${{ github.event.client_payload.service}}",
                "status": "succeeded",
                "result": "pass"
              },
              "source": "github",
              "specversion": "1.0",
              "type": "sh.keptn.event.enable-feature.finished",
              "shkeptncontext": "${{ github.event.client_payload.shkeptncontext }}",
              "triggeredid": "${{ github.event.client_payload.id }}"
            }
        END
        )
        echo "json=$json"
        curl -X POST "${{ secrets.KEPTN_API_URL }}/v1/event" -H "Content-Type: application/json" -H "accept: application/json" -H "x-token: ${{ secrets.KEPTN_API_TOKEN }}" -d "$json"
